## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and keep 'NAME' this time.
application_df = application_df.drop(columns= ['EIN'])
application_df.head()

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

NAME                      19568
APPLICATION_TYPE             17
AFFILIATION                   6
CLASSIFICATION               71
USE_CASE                      5
ORGANIZATION                  4
STATUS                        2
INCOME_AMT                    9
SPECIAL_CONSIDERATIONS        2
ASK_AMT                    8747
IS_SUCCESSFUL                 2
dtype: int64

In [4]:
#Look at NAME value counts for binning (added step for optimization)
name_counts = application_df['NAME'].value_counts()
name_counts

PARENT BOOSTER USA INC                                                  1260
TOPS CLUB INC                                                            765
UNITED STATES BOWLING CONGRESS INC                                       700
WASHINGTON STATE UNIVERSITY                                              492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                          408
                                                                        ...
ST LOUIS SLAM WOMENS FOOTBALL                                              1
AIESEC ALUMNI IBEROAMERICA CORP                                            1
WEALLBLEEDRED ORG INC                                                      1
AMERICAN SOCIETY FOR STANDARDS IN MEDIUMSHIP & PSYCHICAL INVESTIGATI       1
WATERHOUSE CHARITABLE TR                                                   1
Name: NAME, Length: 19568, dtype: int64

In [5]:
# Adjust which value counts to look at to determine cutoff at NAME value counts
application_df['NAME'].value_counts().loc[lambda x : x>50]

PARENT BOOSTER USA INC                                                1260
TOPS CLUB INC                                                          765
UNITED STATES BOWLING CONGRESS INC                                     700
WASHINGTON STATE UNIVERSITY                                            492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                        408
PTA TEXAS CONGRESS                                                     368
SOROPTIMIST INTERNATIONAL OF THE AMERICAS INC                          331
ALPHA PHI SIGMA                                                        313
TOASTMASTERS INTERNATIONAL                                             293
MOST WORSHIPFUL STRINGER FREE AND ACCEPTED MASONS                      287
LITTLE LEAGUE BASEBALL INC                                             277
INTERNATIONAL ASSOCIATION OF LIONS CLUBS                               266
MOMS CLUB                                                              210
INTERNATIONAL ASSOCIATION OF SHEET METAL AIR RAIL & TRANSPORTATION     206
AMERICAN ASSOCIATION OF UNIVERSITY WOMEN                               197
FARMERS EDUCATIONAL AND COOPERATIVE UNION OF AMERICA                   166
KNIGHTS OF COLUMBUS                                                    158
HABITAT FOR HUMANITY INTERNATIONAL INC                                 154
TENNESSEE ORDER OF THE EASTERN STAR                                    151
VETERANS OF FOREIGN WARS OF THE UNITED STATES AUXILIARY                144
PTA UTAH CONGRESS                                                      140
THE UNITED STATES PONY CLUBS INC                                       136
CIVITAN INTERNATIONAL                                                  131
SIGMA BETA DELTA INC                                                   127
HONOR SOCIETY OF PHI KAPPA PHI                                         107
MONTANA 4-H FOUNDATION INC                                             107
WASHINGTON STATE GRANGE                                                106
UNIVERSITY OF WYOMING                                                  105
DEMOLAY INTERNATIONAL                                                  104
SERTOMA INC                                                            103
AIR FORCE ASSOCIATION                                                   99
WORKERS UNITED                                                          97
GAMMA THETA UPSILON                                                     92
INTERNATIONAL ASSOCIATION OF FIRE FIGHTERS                              91
SOCIETY OF SAINT VINCENT DE PAUL COUNCIL OF LOS ANGELES                 87
ROTARY INTERNATIONAL                                                    84
CALIFORNIA GARDEN CLUBS INC                                             76
SWEET ADELINES INTERNATIONAL                                            73
DISABLED AMERICAN VETERANS                                              73
KLEIN SUPPORT GROUPS INC                                                69
CLEARCREEK I S D SUPPORT GROUPS                                         60
VFW AUXILIARY DEPARTMENT OF OKLAHOMA INC                                58
DEPARTMENT OF KANSAS LADIES AUXILIARY TO THE VFW OF THE US INC          57
CISD EDUCATIONAL SUPPORT GROUPS INC                                     57
SONS OF CONFEDERATE VETERANS INC                                        56
SLOW FOOD USA INC                                                       55
NATIONAL YOUNG MENS SERVICE LEAGUE                                      54
AMATEUR ATHLETIC UNION OF THE UNITED STATES                             52
LAMBDA THETA ALPHA                                                      52
Name: NAME, dtype: int64

In [6]:
# Choose a cutoff value and create a list of NAMES to be replaced
# use the variable name `names_types_to_replace`
names_to_replace = list(name_counts[name_counts<50].index)

# Replace in dataframe
for name in names_to_replace:
    application_df['NAME'] = application_df['NAME'].replace(name,"Other")

# Check to make sure binning was successful
application_df['NAME'].value_counts()

Other                                                                 24545
PARENT BOOSTER USA INC                                                 1260
TOPS CLUB INC                                                           765
UNITED STATES BOWLING CONGRESS INC                                      700
WASHINGTON STATE UNIVERSITY                                             492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                         408
PTA TEXAS CONGRESS                                                      368
SOROPTIMIST INTERNATIONAL OF THE AMERICAS INC                           331
ALPHA PHI SIGMA                                                         313
TOASTMASTERS INTERNATIONAL                                              293
MOST WORSHIPFUL STRINGER FREE AND ACCEPTED MASONS                       287
LITTLE LEAGUE BASEBALL INC                                              277
INTERNATIONAL ASSOCIATION OF LIONS CLUBS                                266
MOMS CLUB                                                               210
INTERNATIONAL ASSOCIATION OF SHEET METAL AIR RAIL & TRANSPORTATION      206
AMERICAN ASSOCIATION OF UNIVERSITY WOMEN                                197
FARMERS EDUCATIONAL AND COOPERATIVE UNION OF AMERICA                    166
KNIGHTS OF COLUMBUS                                                     158
HABITAT FOR HUMANITY INTERNATIONAL INC                                  154
TENNESSEE ORDER OF THE EASTERN STAR                                     151
VETERANS OF FOREIGN WARS OF THE UNITED STATES AUXILIARY                 144
PTA UTAH CONGRESS                                                       140
THE UNITED STATES PONY CLUBS INC                                        136
CIVITAN INTERNATIONAL                                                   131
SIGMA BETA DELTA INC                                                    127
MONTANA 4-H FOUNDATION INC                                              107
HONOR SOCIETY OF PHI KAPPA PHI                                          107
WASHINGTON STATE GRANGE                                                 106
UNIVERSITY OF WYOMING                                                   105
DEMOLAY INTERNATIONAL                                                   104
SERTOMA INC                                                             103
AIR FORCE ASSOCIATION                                                    99
WORKERS UNITED                                                           97
GAMMA THETA UPSILON                                                      92
INTERNATIONAL ASSOCIATION OF FIRE FIGHTERS                               91
SOCIETY OF SAINT VINCENT DE PAUL COUNCIL OF LOS ANGELES                  87
ROTARY INTERNATIONAL                                                     84
CALIFORNIA GARDEN CLUBS INC                                              76
SWEET ADELINES INTERNATIONAL                                             73
DISABLED AMERICAN VETERANS                                               73
KLEIN SUPPORT GROUPS INC                                                 69
CLEARCREEK I S D SUPPORT GROUPS                                          60
VFW AUXILIARY DEPARTMENT OF OKLAHOMA INC                                 58
CISD EDUCATIONAL SUPPORT GROUPS INC                                      57
DEPARTMENT OF KANSAS LADIES AUXILIARY TO THE VFW OF THE US INC           57
SONS OF CONFEDERATE VETERANS INC                                         56
SLOW FOOD USA INC                                                        55
NATIONAL YOUNG MENS SERVICE LEAGUE                                       54
AMATEUR ATHLETIC UNION OF THE UNITED STATES                              52
LAMBDA THETA ALPHA                                                       52
UNITED FEDERATION OF DOLL CLUBS INC                                      50
UNIVERSITY OF FLORIDA                                                    50
Name: NAME, dtype: int64

In [7]:
# Look at APPLICATION_TYPE value counts for binning
app_counts = application_df['APPLICATION_TYPE'].value_counts()
app_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [8]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(app_counts[app_counts<500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [9]:
# Look at CLASSIFICATION value counts for binning
class_counts = application_df['CLASSIFICATION'].value_counts()
class_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [10]:
# You may find it helpful to look at CLASSIFICATION value counts >1
application_df['CLASSIFICATION'].value_counts().loc[lambda x : x>1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [11]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(class_counts[class_counts<1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [12]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_AIR FORCE ASSOCIATION,NAME_ALPHA PHI SIGMA,NAME_AMATEUR ATHLETIC UNION OF THE UNITED STATES,NAME_AMATEUR ATHLETIC UNION OF THE UNITED STATES INC,NAME_AMERICAN ASSOCIATION OF UNIVERSITY WOMEN,NAME_CALIFORNIA GARDEN CLUBS INC,NAME_CISD EDUCATIONAL SUPPORT GROUPS INC,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [13]:
# Split our preprocessed data into our features and target arrays
y = application_df['IS_SUCCESSFUL'].values
X = application_df.drop(columns = ['IS_SUCCESSFUL']).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [14]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [15]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features = len( X_train_scaled[0])
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=80, activation="relu", input_dim=input_features))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=30, activation="relu", input_dim=input_features))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                7680

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 10141 (39.61 KB)
Trainable params: 10141 (39.61 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [16]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [17]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5021 - accuracy: 0.7483
Epoch 2/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4788 - accuracy: 0.7644
Epoch 3/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4763 - accuracy: 0.7654
Epoch 4/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4739 - accuracy: 0.7668
Epoch 5/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4726 - accuracy: 0.7678
Epoch 6/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4712 - accuracy: 0.7701
Epoch 7/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4707 - accuracy: 0.7704
Epoch 8/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4696 - accuracy: 0.7693
Epoch 9/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4692 - accuracy: 0.7697
Epoch 10/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4685 - accuracy: 0.7706
Epoch 11/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4683 - accuracy: 0.7712
Epoch 12/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4677 - accuracy: 0.7722
Epoch 13/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4671 - accuracy: 0.7720
Epoch 14/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4666 - accuracy: 0.7724
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4662 - accuracy: 0.7731
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4661 - accuracy: 0.7711
Epoch 17/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4656 - accuracy: 0.7730
Epoch 18/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4660 - accuracy: 0.7719
Epoch 19/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4647 - accuracy: 0.7738
Epoch 20/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4644 - accuracy: 0.7727
Epoch 21/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4643 - accuracy: 0.7724
Epoch 22/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4638 - accuracy: 0.7732
Epoch 23/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4637 - accuracy: 0.7738
Epoch 24/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4632 - accuracy: 0.7748
Epoch 25/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4629 - accuracy: 0.7740
Epoch 26/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4629 - accuracy: 0.7744
Epoch 27/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4628 - accuracy: 0.7748
Epoch 28/50
804/804 [==============================] - 4s 4ms/step - loss: 0.4626 - accuracy: 0.7746
Epoch 29/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4622 - accuracy: 0.7744
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4620 - accuracy: 0.7747
Epoch 31/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4615 - accuracy: 0.7750
Epoch 32/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4614 - accuracy: 0.7747
Epoch 33/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4615 - accuracy: 0.7753
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4610 - accuracy: 0.7752
Epoch 35/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4608 - accuracy: 0.7755
Epoch 36/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4606 - accuracy: 0.7749
Epoch 37/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4608 - accuracy: 0.7752
Epoch 38/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4607 - accuracy: 0.7757
Epoch 39/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4603 - accuracy: 0.7749
Epoch 40/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4600 - accuracy: 0.7756
Epoch 41/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4600 - accuracy: 0.7757
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4603 - accuracy: 0.7752
Epoch 43/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4592 - accuracy: 0.7757
Epoch 44/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4596 - accuracy: 0.7758
Epoch 45/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4593 - accuracy: 0.7757
Epoch 46/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4592 - accuracy: 0.7762
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4589 - accuracy: 0.7748
Epoch 48/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4591 - accuracy: 0.7766
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4592 - accuracy: 0.7755
Epoch 50/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4590 - accuracy: 0.7756

In [18]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.4856 - accuracy: 0.7647 - 516ms/epoch - 2ms/step
Loss: 0.48556485772132874, Accuracy: 0.7646647095680237

Optimization techniques added:
1. Keeping the NAME column
2. Binning the NAME column
3. Decreasing the amount of epochs

The addition of these changes improved accuracy from 0.7301 to 0.7647 and also decreased loss from 0.5605 to 0.4856.

In [19]:
# Export our model to HDF5 file
from google.colab import files
nn.save('AlphabetSoupCharity_Optimization.h5')
files.download('AlphabetSoupCharity_Optimization.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(